export const SET_CURRENT_LANGUAGE = 'FULL/SET_CURRENT_LANGUAGE'
export const SET_LANGUAGE_VARIABLES = 'FULL/SET_LANGUAGE_VARIABLES'
export const SET_DATE = 'FULL/SET_DATE'
export const SET_DATA = 'FULL/SET_DATA'
